{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "robot-diagnosis.fullname" . }}
  labels:
    {{- include "robot-diagnosis.labels" . | nindent 4 }}
  annotations:
    {{- include "robot-diagnosis.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "robot-diagnosis.fullname" $ }}-{{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
{{- end }}
